Improve legibility and formatting of code
StivDC/CM1101 pull request #1
Opened 2018-10-28 19:15 UTC by Chuzzy

Pls accept men 😃

2018-10-28 22:20 UTC, StivDC commented
Hi 👍 😄 👉 📈

2018-10-28 22:21 UTC, StivDC reviewed
💯 nice code!

2018-10-28 22:24 UTC, StivDC requested changes
Make cool variable names or no accept 😄 👍 🥇

2022-10-11 16:58 UTC, Chuzzy commented
:finnadie:

2022-10-11 16:58 UTC, closed without merging